### ISSUE TITLE
Why a custom language ?

### ISSUE THREAD

**Issue by rrousselGit** [andrewackerman/flui#1]
Self-explicit issue : 

Why not using yaml instead of a custom language?

```yaml
Stack: 
  alignment: Alignment(0, 0.5)
  children: 
    - Positionned.fill: 
        child: 
          Container: 
            color: Colors.red
    - Container: 
        height: 50
        with: 50
```

yaml is already supported by most IDE and it should be pretty straightforward to add auto-complete for them too. 

Or html too, that would work.
